server.port=8080
spring.application.name=consuhelp-backend

# Gemini configuration
# If the environment variable GEMINI_API_KEY is not defined, it defaults to 'mock-mode'
spring.ai.google.genai.api-key=${GEMINI_API_KEY:AIzaSyBenIFqHkIPqWu84CJs5axVhRZpILZ2yaM}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
